#!/usr/bin/env bash

set -euo pipefail

SCRIPTPATH=$( dirname "$(realpath "$0")" )

errecho() {
    >&2 echo "${@//$'\n'/}"
}

display_help() {
	echo "Usage:"
    echo "  kubectl batch <subcommand>"
    echo
    echo "Commands:"
    echo "  help               show this help message"
    echo "  exec               execute command among pods"
    echo "  upload             upload local file to multiple pods"
    echo "  download           download files from multiple pods to local"
    echo
    echo "Homepage:"
    echo "  <https://github.com/major1201/kubectl-batch>"
}

main() {
    case "${1-help}" in
    -h|--help|help)
        display_help
        exit
        ;;
    exec|download|upload)
        subcmd=$1
        shift
        "${SCRIPTPATH}/kb${subcmd}" "$@"
        ;;
    *)
        errecho "Unknown command $1"
        display_help
        exit 1
        ;;
    esac
}

main "$@"
